### ISSUE TITLE
Infinite Non Steam games loading

### ISSUE THREAD

**Issue by JesusJMUJI** [Tormak9970/Steam-Art-Manager#221] opened 2024-11-10 12:07 UTC
**Describe the bug**
I'm having a bug where SARM is not able to load 'Non Steam' games, it's on a permanent load loop (it seems). Steam games load fine except 'Non Steam'. 

**To Reproduce**
1. Load SARM.
2. Click on 'Non Steam' when SRAM finishes loading.
3. SARM never loads again.

**Expected behavior**
Being able to load 'Non Steam' games and modify their game art.

**Screenshots**
![image](https://github.com/user-attachments/assets/99bb46e1-af03-4fcb-8c82-0f3e5d64c856)

![image](https://github.com/user-attachments/assets/b1dde140-37c8-44b1-a87d-8eb5ba41db15)

**Logs:**
[Steam Art Manager] [11:12:32] [INFO]: Initialized logging file
[Steam Art Manager] [11:12:32] [INFO]: Finished checking settings for new app version and/or migration.
[Steam Art Manager] [11:12:32] [INFO]: Added c:/program files (x86)/steam to scope.
[Steam Art Manager] [11:12:32] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [11:12:32] [INFO]: Loaded 3 steam users.
[Steam Art Manager] [11:12:32] [INFO]: Initialized CacheController.
[Steam Art Manager] [11:12:32] [INFO]: Loaded 0 custom game names.
[Steam Art Manager] [11:12:32] [INFO]: Finished loading app settings.
[Steam Art Manager] [11:12:32] [INFO]: App setup complete.
[Steam Art Manager] [11:12:32] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [11:12:32] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [11:12:32] [INFO]: shortcuts.vdf exists, reading...
[Steam Art Manager] [11:12:32] [INFO]: Updated setting steamInstallPath to "C:/Program Files (x86)/Steam".
[Steam Art Manager] [11:12:32] [INFO]: Updated setting debugMode to false.
[Steam Art Manager] [11:12:32] [INFO]: Loaded non-steam games.
[Steam Art Manager] [11:12:32] [INFO]: Getting steam grids folder...
[Steam Art Manager] [11:12:32] [INFO]: Grids loaded.
[Steam Art Manager] [11:12:32] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [11:12:32] [INFO]: Library Cache loaded.
[Steam Art Manager] [11:12:32] [INFO]: Cached logo positions for 31 games.
[Steam Art Manager] [11:12:33] [INFO]: Skipping update v3.10.1.
[Steam Art Manager] [11:12:34] [INFO]: Loaded 302 games from Steam Community page.
[Steam Art Manager] [11:12:39] [INFO]: Added c:/program files (x86)/steam to scope.
[Steam Art Manager] [11:12:42] [INFO]: Reverting settings...
[Steam Art Manager] [11:12:42] [INFO]: Reverted settings.
[Steam Art Manager] [11:12:49] [ERROR]: MainWindow: Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase') in https://tauri.localhost/assets/main-f03812db.js at 24:15107.

**System information (please complete the following information):**
 - OS: Windows 11
 - Version: [SARM v3.10.3](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.10.3)

**Comment by Tormak9970** [comment] 2024-11-13 15:28
I'll look into this and try to get a fix out soon. Thanks for providing such a detailed issue report!

**Comment by Tormak9970** [comment] 2024-11-14 16:23
@JesusJMUJI How were these non-steam games added? I can't seem to reproduce this issue

**Comment by JesusJMUJI** [comment] 2024-11-14 16:25
> @JesusJMUJI How were these non-steam games added? I can't seem to reproduce this issue

To be honest, I don't remember. Is there a way to completely reset all app data so I can test it again?

**Comment by Tormak9970** [comment] 2024-11-14 16:30
Can you also open the `C:\Program Files (x86)\Steam\userdata\YOUR_STEAM_ID\config\shortcuts.vdf` file in notepad and screenshot it? I think the issue is the `AppName` value shown here has a different name in older versions
![image](https://github.com/user-attachments/assets/2ac90bf8-9099-4219-bb0b-bedceff152cf)

**Comment by JesusJMUJI** [comment] 2024-11-14 16:51
> Can you also open the `C:\Program Files (x86)\Steam\userdata\YOUR_STEAM_ID\config\shortcuts.vdf` file in notepad and screenshot it? I think the issue is the `AppName` value shown here has a different field name in older versions ![image](https://private-user-images.githubusercontent.com/63308171/386282838-2ac90bf8-9099-4219-bb0b-bedceff152cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDI5NzQsIm5iZiI6MTczMTYwMjY3NCwicGF0aCI6Ii82MzMwODE3MS8zODYyODI4MzgtMmFjOTBiZjgtOTA5OS00MjE5LWJiMGItYmVkY2VmZjE1MmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE2NDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNmEzNzdmYzI1Y2Q2YjJhZWFmZmFjMjZkNDFkMWQ3NWZkYThlOWMxYWY0MGIwNzg4OGIzMDRlNDNhOTdiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X1diSRgrQKzLAKR0kL9rGrqVm3LpVsZ9lQOakZTbry0)

![image](https://github.com/user-attachments/assets/948dc06c-a96b-4448-9004-5fa318bf3d38)

I have a huge file, and a lot of non-steam games added; so perhaps I have a route that perhaps has a weird name?

**Comment by Tormak9970** [comment] 2024-11-14 18:06
> > Can you also open the `C:\Program Files (x86)\Steam\userdata\YOUR_STEAM_ID\config\shortcuts.vdf` file in notepad and screenshot it? I think the issue is the `AppName` value shown here has a different field name in older versions ![image](https://private-user-images.githubusercontent.com/63308171/386282838-2ac90bf8-9099-4219-bb0b-bedceff152cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDI5NzQsIm5iZiI6MTczMTYwMjY3NCwicGF0aCI6Ii82MzMwODE3MS8zODYyODI4MzgtMmFjOTBiZjgtOTA5OS00MjE5LWJiMGItYmVkY2VmZjE1MmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE2NDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNmEzNzdmYzI1Y2Q2YjJhZWFmZmFjMjZkNDFkMWQ3NWZkYThlOWMxYWY0MGIwNzg4OGIzMDRlNDNhOTdiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X1diSRgrQKzLAKR0kL9rGrqVm3LpVsZ9lQOakZTbry0)
> 
> ![image](https://private-user-images.githubusercontent.com/113539857/386290190-948dc06c-a96b-4448-9004-5fa318bf3d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDc4NjQsIm5iZiI6MTczMTYwNzU2NCwicGF0aCI6Ii8xMTM1Mzk4NTcvMzg2MjkwMTkwLTk0OGRjMDZjLWE5NmItNDQ0OC05MDA0LTVmYTMxOGJmM2QzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxODA2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGNmYjUwYzk1ZDAxMjBmYzZlZWUwOTQ1NmIzYjZmYTczMzRmNDVlYmJjZTUyYzAxYjczYzY1MTAwM2NmOGM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TQtsh_3fKYfkyuAOy3M_7kaJL6kToAW26asdBfmyQqs)
> 
> I have a huge file, and a lot of non-steam games added; so perhaps I have a route that perhaps has a weird name? I could try deleting all my non-steam games and trying again. And SARM still spits out the same error after resetting it; so it points to the thing you suggested.

ok perfect, I haven't accounted for `appName`, only `appname` and `AppName`, so that's likely the issue

**Comment by JesusJMUJI** [comment] 2024-11-14 18:08
> > > Can you also open the `C:\Program Files (x86)\Steam\userdata\YOUR_STEAM_ID\config\shortcuts.vdf` file in notepad and screenshot it? I think the issue is the `AppName` value shown here has a different field name in older versions ![image](https://private-user-images.githubusercontent.com/63308171/386282838-2ac90bf8-9099-4219-bb0b-bedceff152cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDI5NzQsIm5iZiI6MTczMTYwMjY3NCwicGF0aCI6Ii82MzMwODE3MS8zODYyODI4MzgtMmFjOTBiZjgtOTA5OS00MjE5LWJiMGItYmVkY2VmZjE1MmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDE2NDQzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNmEzNzdmYzI1Y2Q2YjJhZWFmZmFjMjZkNDFkMWQ3NWZkYThlOWMxYWY0MGIwNzg4OGIzMDRlNDNhOTdiNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.X1diSRgrQKzLAKR0kL9rGrqVm3LpVsZ9lQOakZTbry0)
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/113539857/386290190-948dc06c-a96b-4448-9004-5fa318bf3d38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2MDc4NjQsIm5iZiI6MTczMTYwNzU2NCwicGF0aCI6Ii8xMTM1Mzk4NTcvMzg2MjkwMTkwLTk0OGRjMDZjLWE5NmItNDQ0OC05MDA0LTVmYTMxOGJmM2QzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNFQxODA2MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGNmYjUwYzk1ZDAxMjBmYzZlZWUwOTQ1NmIzYjZmYTczMzRmNDVlYmJjZTUyYzAxYjczYzY1MTAwM2NmOGM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.TQtsh_3fKYfkyuAOy3M_7kaJL6kToAW26asdBfmyQqs)
> > I have a huge file, and a lot of non-steam games added; so perhaps I have a route that perhaps has a weird name? I could try deleting all my non-steam games and trying again. And SARM still spits out the same error after resetting it; so it points to the thing you suggested.
> 
> ok perfect, I haven't accounted for `appName`, only `appname` and `AppName`, so that's likely the issue

Glad that helped. I guess it should be fixed in the next version? I was thinking of deleting all of my non-steam games, if that was the issue.

**Comment by Tormak9970** [comment] 2024-11-14 18:09
nah, shouldn't need to delete them, I'll have an updated version out in like an hour or so that should just work

**Comment by Tormak9970** [comment] 2024-11-14 18:13
fixed with https://github.com/Tormak9970/Steam-Art-Manager/commit/363bc81c94659383c7ad6084bc01829b454c385f. Will be included in the next release

**Closed by Tormak9970** 2024-11-14 18:13 UTC
Labels: bug
