### ISSUE TITLE
Infinite loading (linux mint)

### ISSUE THREAD

**Issue by JohnGhostly** [Tormak9970/Steam-Art-Manager#139] opened 2023-08-11 07:46 UTC
**Describe the bug**
Infinite loading bug. 

**To Reproduce**
1. Installed on linux mint (running with hrough kde plasma desktop environment) with dependencies

**Expected behavior**
Load within at least a minute of startup

**Screenshots**
![Screenshot_20230811_024012](https://github.com/Tormak9970/Steam-Art-Manager/assets/25890707/ec66b717-dab1-4dfb-8246-690e52e12fd2)

**Logs:**
`[Steam Art Manager] [2:42:47] [INFO]: Initialized logging file
[Steam Art Manager] [2:42:47] [INFO]: Added Steam directory to scope.
[Steam Art Manager] [2:42:47] [INFO]: Initializing CacheController...
[Steam Art Manager] [2:42:47] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [2:42:47] [INFO]: Loaded 1 steam users.
[Steam Art Manager] [2:42:47] [INFO]: Found cache dir.
[Steam Art Manager] [2:42:47] [INFO]: Found grids cache dir.
[Steam Art Manager] [2:42:47] [INFO]: Found Capsule cache dir.
[Steam Art Manager] [2:42:47] [INFO]: App setup complete.
[Steam Art Manager] [2:42:47] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [2:42:47] [INFO]: Loading non-steam games...
[Steam Art Manager] [2:42:47] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [2:42:47] [INFO]: shortcuts.vdf exists, reading...
[Steam Art Manager] [2:42:47] [INFO]: Loaded non-steam games.
[Steam Art Manager] [2:42:47] [INFO]: Getting steam games...
[Steam Art Manager] [2:42:47] [INFO]: Getting steam grids folder...
[Steam Art Manager] [2:42:47] [INFO]: Found Wide Capsule cache dir.
[Steam Art Manager] [2:42:47] [INFO]: Found Hero cache dir.
[Steam Art Manager] [2:42:47] [INFO]: Found Logo cache dir.
[Steam Art Manager] [2:42:47] [INFO]: Found Icon cache dir.
[Steam Art Manager] [2:42:47] [INFO]: Initialized CacheController.
`
(log does not seem to provide any useful information)

**System information (please complete the following information):**
 - OS: Linux mint
 - Version 21.2

**Additional information**
I haven't a clue about what could be causing this
Api key for steamgridDB and Steam are both set

**Comment by Tormak9970** [comment] 2023-08-14 16:48
I'll look into this. I was able to run it on a linux mint VM, so I suspect its related to your setup.

**Comment by JohnGhostly** [comment] 2023-08-15 11:57
It probably is. theres some oddities related to how steam was installed. apparently its not in a common directory.

**Comment by Tormak9970** [comment] 2023-08-15 14:07
> It probably is. theres some oddities related to how steam was installed. apparently its not in a common directory.

Aah. I need to add support for non standard install locations. Where is yours installed? (you can prob solve your problems by making a symlink to the expected locations)

**Comment by Tormak9970** [comment] 2023-08-19 20:22
Custom Steam Path support has been implemented as of https://github.com/Tormak9970/Steam-Art-Manager/commit/3bec5628ad4b5f0fbb932a800c3abc17147b2543 and will be included in the next update

**Comment by JohnGhostly** [comment] 2023-08-21 01:15
> > It probably is. theres some oddities related to how steam was installed. apparently its not in a common directory.
> 
> Aah. I need to add support for non standard install locations. Where is yours installed? (you can prob solve your problems by making a symlink to the expected locations)

My steam folder is located in /home/(user)/.steam/steam
I have no idea why its installed here rather than 
/home/(user)/.local/share/Steam

**Comment by Tormak9970** [comment] 2023-08-21 02:39
hmm, that's the default location. steam symlinks them. Means I gotta figure out what the actual issue is ig, since its not the path

**Comment by JohnGhostly** [comment] 2023-08-22 03:33
Wheres the console tab? I installed the debug build and I dont see one

**Comment by Tormak9970** [comment] 2023-08-22 12:58
> Wheres the console tab? I installed the debug build and I dont see one

When you open up the inspector, there should be a row of tabs at the top of it. May need to make the app full screen for a moment to see the console tab, but it should be there

**Comment by JohnGhostly** [comment] 2023-08-29 22:22
Can't find it 
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/25890707/26aefbff-2956-4aa7-bd6a-c271339e408b)

**Comment by Tormak9970** [comment] 2023-08-29 22:26
> Can't find it ![image](https://user-images.githubusercontent.com/25890707/264173959-26aefbff-2956-4aa7-bd6a-c271339e408b.png)

you have to first right-click, then hit inspect (or hit ctrl+shift+i), then you should see a new section show up on the bottom or the right side of the app, and the console tab will be in there

**Comment by JohnGhostly** [comment] 2023-08-29 22:32
ctrl+shift+i doesn't seem to do anything.
Im not sure where inspect would be. its not under right click either

**Comment by Tormak9970** [comment] 2023-08-29 23:03
> ctrl+shift+i doesn't seem to do anything. Im not sure where inspect would be. its not under right click either

this is the debug build, right?

**Comment by JohnGhostly** [comment] 2023-09-04 01:22
Correct. I installed it through konsole. I'll try doing a full uninstall and doing it again.

**Comment by Tormak9970** [comment] 2023-09-04 12:44
> Correct. I installed it through konsole. I'll try doing a full uninstall and doing it again.

Alright. Maybe try just downloading the appimage, since maybe there's an issue with the installer script

**Comment by Tormak9970** [comment] 2023-09-09 18:04
@JohnGhostly there was an issue with the installer script, may have been why it wasn't installing debug builds. Fixed it for the next release

**Comment by Tormak9970** [comment] 2023-09-18 14:09
Going to try debugging this with a virtual box again, and see if I can make any progress

**Comment by Tormak9970** [comment] 2023-09-19 15:01
I am unable to reproduce the issue (once steam is installed)
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/63308171/23fd937f-44b6-49e8-94a7-b5fd375309d7)

**Comment by baltimoresports** [comment] 2024-03-14 21:04
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/1420685/ad18c301-95e6-4e11-bdc2-49c00f2e506d)

Same issue with Bazzite (Fedora).

**Comment by baltimoresports** [comment] 2024-03-14 21:07
I get either infinite loading or a white box

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/1420685/ad18c301-95e6-4e11-bdc2-49c00f2e506d)

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/1420685/9d960cad-11a7-4eb2-81d6-7e839e963947)


Same issue with Bazzite (Fedora).

**Comment by Tormak9970** [comment] 2024-03-15 22:30
@baltimoresports can you provide your log file? There's a chance that might indicate what the issue is, I've added better logging in the last few updates

**Comment by baltimoresports** [comment] 2024-03-15 22:41
> @baltimoresports can you provide your log file? There's a chance that might indicate what the issue is, I've added better logging in the last few updates

Not sure if this is right log but I found this under /home/bazzite/.config/steam-rom-manager/logs/main.log

```
[2024-03-14 15:36:12.958] [info]  Checking for update
[2024-03-14 15:36:12.967] [info]  Generated new staging user ID: 0547de0e-0b67-566a-b40b-5a4ae8545d91
[2024-03-14 15:36:14.196] [info]  Update for version 2.4.17 is not available (latest version: 2.4.17, downgrade is disallowed).
```

**Comment by baltimoresports** [comment] 2024-03-15 22:47
> @baltimoresports can you provide your log file? There's a chance that might indicate what the issue is, I've added better logging in the last few updates

Sorry, where can I find the log file on linux. I can only find the appimage in my home.

**Comment by baltimoresports** [comment] 2024-03-15 23:10
Just my steps if it helps...

Install using the latest linux-installer.sh and it installs 2.9.0
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/1420685/ec9e3f01-143b-4718-8de5-eb483a7486d1)

Open for the first time and get prompted to upgrade

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/1420685/980d914c-c291-4920-9307-3558420b8947)

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/1420685/f0ee870e-a5ac-4d9c-b2b7-3cbc8c100946)

**Comment by Tormak9970** [comment] 2024-03-15 23:17
> Just my steps if it helps...
> 
> Install using the latest linux-installer.sh and it installs 2.9.0 ![image](https://private-user-images.githubusercontent.com/1420685/313353336-ec9e3f01-143b-4718-8de5-eb483a7486d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDQ3OTMsIm5iZiI6MTcxMDU0NDQ5MywicGF0aCI6Ii8xNDIwNjg1LzMxMzM1MzMzNi1lYzllM2YwMS0xNDNiLTQ3MTgtOGRlNS1lYjQ4M2E3NDg2ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMjMxNDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMxZmYxMzk2MjI1NTkwODkyMWRkMTU0ZjIzYjEzMDU3ZTRlNzY1ODVlZDgwNzc1NmFiYmEzMTZhM2Q0OWViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9OBr5la25_lsvcHULJt_sBbj2RRgOtcXeJ07hXdKAGQ)
> 
> Open for the first time and get prompted to upgrade
> 
> ![image](https://private-user-images.githubusercontent.com/1420685/313353514-980d914c-c291-4920-9307-3558420b8947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDQ3OTMsIm5iZiI6MTcxMDU0NDQ5MywicGF0aCI6Ii8xNDIwNjg1LzMxMzM1MzUxNC05ODBkOTE0Yy1jMjkxLTQ5MjAtOTMwNy0zNTU4NDIwYjg5NDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMjMxNDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkwZmEwNWRkMTUwODc0NTU4MTdlODU4ODJiZDBkMzFmNDQ1YjM4MGNhZjE0YjhiY2FlY2ZiNzU5YTg5YWE2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fil--Qoh_9yVp97DgHN7J3VZLm827-EI6LtTUbxjsAU)
> 
> ![image](https://private-user-images.githubusercontent.com/1420685/313354094-93194d30-3b15-491e-becc-988b7104edf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDQ3OTMsIm5iZiI6MTcxMDU0NDQ5MywicGF0aCI6Ii8xNDIwNjg1LzMxMzM1NDA5NC05MzE5NGQzMC0zYjE1LTQ5MWUtYmVjYy05ODhiNzEwNGVkZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMjMxNDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBkNzRmM2VmYjc3MmMzZDljZDkzMzM2N2VkMWZhZDI1YzZhMjZmYTU0MDdiYTZkZTQzMzY0MzQ3NGFiMTVmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.thuc7J9VXhQKHHNHah5jht5NX9c5Q4jvZJz2h6uc8no)
> 
> ![image](https://private-user-images.githubusercontent.com/1420685/313353698-64f5b5f1-05d7-4b66-a88b-40cc692fc86d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDQ3OTMsIm5iZiI6MTcxMDU0NDQ5MywicGF0aCI6Ii8xNDIwNjg1LzMxMzM1MzY5OC02NGY1YjVmMS0wNWQ3LTRiNjYtYTg4Yi00MGNjNjkyZmM4NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMjMxNDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTA3ZjRjYmUwNjVjODRiYmYzYzg5MTVkZjZiMzRiMTNmYzQxNDU1MDZjM2ZhN2Q2MGQyNjQ2MjY3NTdhNTJmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YoBzNhSNSXHmCUxkeCdkpGhC2lmCRpSE_Dtn9X1BV1s)
> 
> If it helps my steam path is: /home/bazzite/.steam/steam/
> 
> One thing I did notice is 2.9.0 pulls up my steam username in the dropdown, but 3.0.0 does not.

Hmm, it looks like the latest release didn't build properly (It had fixes for some settings issues), and this seems to be related to saving settings. I'm gonna try and fix that release right now. Once I do I'll update this issue, but if that works then something related to the updater is also broken, if not, I'll try and look into it more

**Comment by baltimoresports** [comment] 2024-03-15 23:18
> > Just my steps if it helps...
> > Install using the latest linux-installer.sh and it installs 2.9.0 ![image](https://private-user-images.githubusercontent.com/1420685/313353336-ec9e3f01-143b-4718-8de5-eb483a7486d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDQ3OTMsIm5iZiI6MTcxMDU0NDQ5MywicGF0aCI6Ii8xNDIwNjg1LzMxMzM1MzMzNi1lYzllM2YwMS0xNDNiLTQ3MTgtOGRlNS1lYjQ4M2E3NDg2ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMjMxNDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMxZmYxMzk2MjI1NTkwODkyMWRkMTU0ZjIzYjEzMDU3ZTRlNzY1ODVlZDgwNzc1NmFiYmEzMTZhM2Q0OWViMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.9OBr5la25_lsvcHULJt_sBbj2RRgOtcXeJ07hXdKAGQ)
> > Open for the first time and get prompted to upgrade
> > ![image](https://private-user-images.githubusercontent.com/1420685/313353514-980d914c-c291-4920-9307-3558420b8947.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDQ3OTMsIm5iZiI6MTcxMDU0NDQ5MywicGF0aCI6Ii8xNDIwNjg1LzMxMzM1MzUxNC05ODBkOTE0Yy1jMjkxLTQ5MjAtOTMwNy0zNTU4NDIwYjg5NDcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMjMxNDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTkwZmEwNWRkMTUwODc0NTU4MTdlODU4ODJiZDBkMzFmNDQ1YjM4MGNhZjE0YjhiY2FlY2ZiNzU5YTg5YWE2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fil--Qoh_9yVp97DgHN7J3VZLm827-EI6LtTUbxjsAU)
> > ![image](https://private-user-images.githubusercontent.com/1420685/313354094-93194d30-3b15-491e-becc-988b7104edf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDQ3OTMsIm5iZiI6MTcxMDU0NDQ5MywicGF0aCI6Ii8xNDIwNjg1LzMxMzM1NDA5NC05MzE5NGQzMC0zYjE1LTQ5MWUtYmVjYy05ODhiNzEwNGVkZjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMjMxNDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzBkNzRmM2VmYjc3MmMzZDljZDkzMzM2N2VkMWZhZDI1YzZhMjZmYTU0MDdiYTZkZTQzMzY0MzQ3NGFiMTVmNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.thuc7J9VXhQKHHNHah5jht5NX9c5Q4jvZJz2h6uc8no)
> > ![image](https://private-user-images.githubusercontent.com/1420685/313353698-64f5b5f1-05d7-4b66-a88b-40cc692fc86d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1NDQ3OTMsIm5iZiI6MTcxMDU0NDQ5MywicGF0aCI6Ii8xNDIwNjg1LzMxMzM1MzY5OC02NGY1YjVmMS0wNWQ3LTRiNjYtYTg4Yi00MGNjNjkyZmM4NmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTVUMjMxNDUzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTA3ZjRjYmUwNjVjODRiYmYzYzg5MTVkZjZiMzRiMTNmYzQxNDU1MDZjM2ZhN2Q2MGQyNjQ2MjY3NTdhNTJmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YoBzNhSNSXHmCUxkeCdkpGhC2lmCRpSE_Dtn9X1BV1s)
> > If it helps my steam path is: /home/bazzite/.steam/steam/
> > One thing I did notice is 2.9.0 pulls up my steam username in the dropdown, but 3.0.0 does not.
> 
> Hmm, it looks like the latest release didn't build properly (It had fixes for some settings issues), and this seems to be related to saving settings. I'm gonna try and fix that release right now. Once I do I'll update this issue, but if that works then something related to the updater is also broken, if not, I'll try and look into it more

Thank you!

**Comment by Tormak9970** [comment] 2024-03-15 23:36
@baltimoresports can you try the new release after uninstalling your current one?

**Comment by baltimoresports** [comment] 2024-03-15 23:42
Sorry no luck. 

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/1420685/0325df2f-9a48-4798-8b5c-37196838ecfe)

**Comment by Tormak9970** [comment] 2024-03-15 23:45
what happens if you delete your `settings.json` file? it should be in `~/bazzite/.config/dev.tormak.steam-art-manager`

**Comment by baltimoresports** [comment] 2024-03-15 23:47
Nothing there...

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/1420685/7660e68b-f416-4c0c-b57c-796d598ae165)

**Comment by Tormak9970** [comment] 2024-03-15 23:53
what happens if you put this in that folder? 
[settings.json](https://github.com/Tormak9970/Steam-Art-Manager/files/14621638/settings.json)
(its the default settings.json that should get created)

**Comment by baltimoresports** [comment] 2024-03-15 23:57
> what happens if you put this in that folder? [settings.json](https://github.com/Tormak9970/Steam-Art-Manager/files/14621638/settings.json) (its the default settings.json that should get created)

Same freeze unfortunately.

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/1420685/73f14cfb-71f2-4785-8406-ec8110f9b603)

**Comment by Tormak9970** [comment] 2024-03-15 23:59
damn, this is annoying. Its working fine on my SteamOS install (my only linux machine unfortunately). I'll look into it some more, thanks for the help

**Comment by Tormak9970** [comment] 2024-03-16 00:07
I'm going to try running bazzite on a VM and see if I can reproduce this problem and fix it

**Comment by Tormak9970** [comment] 2024-03-16 01:55
This appears to be an issue with the framework I'm using. I need to do some troubleshooting

**Comment by baltimoresports** [comment] 2024-03-16 11:08
> This appears to be an issue with the framework I'm using. I need to do some troubleshooting

Thank you for the support!

**Comment by Tormak9970** [comment] 2024-03-17 14:59
> > This appears to be an issue with the framework I'm using. I need to do some troubleshooting
> 
> Thank you for the support!

We figured out the problem was bazzite symlinks `/home` to `/var/home`, there's a workaround for it tho, so hopefully this resolves the issue

**Comment by Tormak9970** [comment] 2024-03-17 15:22
@baltimoresports can you try using the appimage from this debug release: https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/debug-3.2.0

**Comment by Tormak9970** [comment] 2024-03-18 17:24
As of https://github.com/Tormak9970/Steam-Art-Manager/commit/5a1dfe291a59d42829b74b596d0c5c434bf4b883 the app is now functioning on bazzite. This fix will be included in the next release, and will also fix any other issues related to symlinks in the paths SARM uses.

**Closed by Tormak9970** 2024-03-18 17:24 UTC
Labels: bug

**Comment by baltimoresports** [comment] 2024-03-20 20:38
> As of [5a1dfe2](https://github.com/Tormak9970/Steam-Art-Manager/commit/5a1dfe291a59d42829b74b596d0c5c434bf4b883) the app is now functioning on bazzite. This fix will be included in the next release, and will also fix any other issues related to symlinks in the paths SARM uses.

You're awesome. Thank you!
