### ISSUE TITLE
Animated artwork is blank in search grid

### ISSUE THREAD

**Issue by jathek** [Tormak9970/Steam-Art-Manager#149] opened 2023-10-13 03:29 UTC
**Describe the bug**
Animated images don't display in the search grid.

**To Reproduce**
1. Search for a game
2. Click on the artwork 
3. All animated options are blank

**Expected behavior**
See the animated artwork

**Screenshots**
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/692914/a1809d37-cbd7-4916-a460-229d4e65765b)

**Logs:**
<details>
<summary>logs</summary>

```
[Steam Art Manager] [22:24:8] [INFO]: Initialized logging file
[Steam Art Manager] [22:24:8] [INFO]: Initializing CacheController...
[Steam Art Manager] [22:24:8] [INFO]: Found cache dir.
[Steam Art Manager] [22:24:8] [INFO]: Found grids cache dir.
[Steam Art Manager] [22:24:8] [INFO]: Added C:/Program Files (x86)/Steam to scope.
[Steam Art Manager] [22:24:8] [INFO]: Found Capsule cache dir.
[Steam Art Manager] [22:24:8] [INFO]: Checking config/loginusers.vdf for current user info.
[Steam Art Manager] [22:24:8] [INFO]: Loaded 1 steam users.
[Steam Art Manager] [22:24:8] [INFO]: Found Wide Capsule cache dir.
[Steam Art Manager] [22:24:8] [INFO]: Loaded 0 custom game names.
[Steam Art Manager] [22:24:8] [INFO]: App setup complete.
[Steam Art Manager] [22:24:8] [INFO]: App loaded. IsOnline: true.
[Steam Art Manager] [22:24:8] [INFO]: Loading non-steam games...
[Steam Art Manager] [22:24:8] [INFO]: Getting steam shortcuts.vdf...
[Steam Art Manager] [22:24:8] [INFO]: shortcuts.vdf does not exist.
[Steam Art Manager] [22:24:8] [INFO]: Loaded non-steam games.
[Steam Art Manager] [22:24:8] [INFO]: Getting steam games...
[Steam Art Manager] [22:24:8] [INFO]: Getting steam grids folder...
[Steam Art Manager] [22:24:8] [INFO]: Found Hero cache dir.
[Steam Art Manager] [22:24:8] [INFO]: Grids loaded.
[Steam Art Manager] [22:24:8] [INFO]: Getting steam library cache folder...
[Steam Art Manager] [22:24:8] [INFO]: Found Logo cache dir.
[Steam Art Manager] [22:24:8] [INFO]: Found Icon cache dir.
[Steam Art Manager] [22:24:8] [INFO]: Initialized CacheController.
[Steam Art Manager] [22:24:8] [INFO]: Library Cache loaded.
[Steam Art Manager] [22:24:8] [INFO]: Cached logo positions for 3 games.
[Steam Art Manager] [22:24:8] [INFO]: Loading games from Steam API...
[Steam Art Manager] [22:24:9] [INFO]: Loaded 561 games from Steam API.
[Steam Art Manager] [22:24:9] [INFO]: Steam games loaded.
[Steam Art Manager] [22:24:14] [INFO]: Fetching grids for game 870780...
[Steam Art Manager] [22:24:14] [INFO]: Need to fetch nonSteam Capsule for 28601.
[Steam Art Manager] [22:24:14] [INFO]: Query: "Capsules for Control Ultimate Edition". Result: 36 grids.
```
</details>

**System information (please complete the following information):**
 - OS: Windows 11 Pro 22H2 22621.2134
 - Version v3.0.0

**Comment by Tormak9970** [comment] 2023-10-17 14:30
@jathek I've experienced this when SGDB is having issues or when my wifi is unstable. Need to add a placeholder, but is this issue reporduceable?

**Comment by Andr3WTF** [comment] 2024-02-12 10:45
same thing... any suggestions?
![Screenshot_5](https://github.com/Tormak9970/Steam-Art-Manager/assets/29490178/dcbb9560-1928-4b12-b0da-81c6a1a0e0b3)

**Comment by Andr3WTF** [comment] 2024-02-12 10:46
also settings in left bar after closing\reopen program not saved...

**Comment by Tormak9970** [comment] 2024-02-12 14:35
> also settings in left bar after closing\reopen program not saved...

Im aware of the settings not saving, that feature will be included in the next update. As to the gifs, I'm not sure. Could be SGDB is having issues, could be your wifi. Ill look into it to confirm its not SARM

**Comment by jathek** [comment] 2024-02-12 20:31
> @jathek I've experienced this when SGDB is having issues or when my wifi is unstable. Need to add a placeholder, but is this issue reporduceable?

very sorry I missed this comment. But it's completely reproducible. I have never once seen animated images work in the grid. If I download it then it displays properly in Steam, but it never works in SAM in the grid. My workaround for now is to click the expand button (two arrows) to view the artwork fullscreen, because then it *does* load in the expanded view. BUT: it only loads if I mouse-click in the window! Otherwise it's still blank in the expanded view. And no matter what I do, the grid is always blank for animated images.

All in all, it's a huge pain to do this stuff compared to just viewing the artwork in the grid.

**Comment by Tormak9970** [comment] 2024-02-12 20:42
> > @jathek I've experienced this when SGDB is having issues or when my wifi is unstable. Need to add a placeholder, but is this issue reporduceable?
> 
> 
> 
> very sorry I missed this comment. But it's completely reproducible. I have never once seen animated images work in the grid. If I download it then it displays properly in Steam, but it never works in SAM in the grid. My workaround for now is to click the expand button (two arrows) to view the artwork fullscreen, because then it *does* load in the expanded view. BUT: it only loads if I mouse-click in the window! Otherwise it's still blank in the expanded view. And no matter what I do, the grid is always blank for animated images.
> 
> 
> 
> All in all, it's a huge pain to do this stuff compared to just viewing the artwork in the grid.

Hmm, then it's definitely an issue with sarm, Ill look into it

**Comment by Andr3WTF** [comment] 2024-02-12 20:48
i switched to cord, but there is no any difference! So i guess, it's not connection related. I can provide any needed information or logs if needed.
![Screenshot_5](https://github.com/Tormak9970/Steam-Art-Manager/assets/29490178/73e59456-47ae-4c66-b411-bab7c8fcb487)

**Comment by Tormak9970** [comment] 2024-02-28 15:09
@jathek what language is your pc set to? is it english? Its possible this is related to that

**Comment by jathek** [comment] 2024-02-28 19:45
> @jathek what language is your pc set to? is it english? Its possible this is related to that

Yes, it is.
![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/692914/a099b9ad-c3dc-4a9b-bfbe-c00cb322ddee)

**Comment by Tormak9970** [comment] 2024-02-28 21:34
> > @jathek what language is your pc set to? is it english? Its possible this is related to that
> 
> 
> 
> Yes, it is.
> 
> ![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/692914/a099b9ad-c3dc-4a9b-bfbe-c00cb322ddee)
> 
> 

Ok good to know, so its not a localization issue. Still trying to figure out the cause for this because I can't seem to reproduce it

**Comment by jathek** [comment] 2024-03-01 06:47
> @jathek Can you check what version of the Microsoft WebView2 you have installed? It can be found here:

![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/692914/39966516-4264-46c2-976c-51fbb8eb5115)

**Comment by Tormak9970** [comment] 2024-03-01 15:09
> > @jathek Can you check what version of the Microsoft WebView2 you have installed? It can be found here:
> 
> 
> 
> SARM doesn't play animated images on either of the two below machines.
> 
> 
> 
> Windows 10 machine:
> 
> ![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/692914/39966516-4264-46c2-976c-51fbb8eb5115)
> 
> Windows 11 machine:
> 
> ![image](https://github.com/Tormak9970/Steam-Art-Manager/assets/692914/66bfa10e-5424-4f29-bb45-dcf5bc1a0cfe)
> 
> 

Hmm,so its not that either. I'll keep looking

**Comment by jathek** [comment] 2024-03-15 23:59
I saw the changelog for 3.2.0 mentions "images now load faster and more reliably", so I installed it just to see if it would fix this issue, but it still persists.

**Comment by Tormak9970** [comment] 2024-03-16 00:00
> I saw the changelog for 3.2.0 mentions "images now load faster and more reliably", so I installed it just to see if it would fix this issue, but it still persists.

Yea that's why I haven't closed this issue, I still haven't figured out how to isolate this or replicate it

**Comment by Tormak9970** [comment] 2024-03-18 18:31
@jathek @Andr3WTF I think I may have found the issue. Can you try the new release https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.2.1 and let me know if the issue persists?

**Comment by Andr3WTF** [comment] 2024-03-18 18:42
> @jathek @Andr3WTF I think I may have found the issue. Can you try the new release https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.2.1 and let me know if the issue persists?

At first look everything looks fine, but sorry have no time test deeper now, need to go
![Screenshot_12](https://github.com/Tormak9970/Steam-Art-Manager/assets/29490178/c00142b3-c682-4e3e-a465-2e9c51f423e0)

**Comment by Tormak9970** [comment] 2024-03-18 18:44
> > @jathek @Andr3WTF I think I may have found the issue. Can you try the new release https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.2.1 and let me know if the issue persists?
> 
> At first look everything looks fine, but sorry have no time test deeper now, need to go ![Screenshot_12](https://private-user-images.githubusercontent.com/29490178/313798929-c00142b3-c682-4e3e-a465-2e9c51f423e0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3ODc3NjEsIm5iZiI6MTcxMDc4NzQ2MSwicGF0aCI6Ii8yOTQ5MDE3OC8zMTM3OTg5MjktYzAwMTQyYjMtYzY4Mi00ZTNlLWE0NjUtMmU5YzUxZjQyM2UwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDE4NDQyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYmYyNTliNDZlMjAwNGI5ZTY4ZjUxMThjNzcwNTRhNzVlNmQ1ZjcyYThjMjllYjZhZDkyOTA4NDE5ZjA3NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UjgWxBcMHb7sZ0Tz7Zjl0sN-tG5preNvKSApQVPDOqE)

No worries, that's all I needed, thank you

**Closed by Tormak9970** 2024-03-18 18:44 UTC
Labels: bug

**Comment by jathek** [comment] 2024-03-18 21:28
> @jathek @Andr3WTF I think I may have found the issue. Can you try the new release [`v3.2.1` (release)](https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v3.2.1) and let me know if the issue persists?

Fixed it for me as well, thanks
